version: 2
jobs:
  api-tests:
    docker:
      - image: circleci/node:10-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: user
          NODE_ENV: test
      - image: mdillon/postgis:9.5
        environment:
          POSTGRES_DB: api_starter_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: user
          JTW_SECRET: secret
    steps:
      - checkout
      - run: |
          yarn &&
          yarn build &&
          yarn test
workflows:
  version: 2
  api:
    jobs:
      - api-tests:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: /^no-build.*/
